### PR TITLE
Test cases for shared library interface

### PR DESCRIPTION
**Pull request by menon-karthik**
I added two test cases - one that mimics the coupling with svSolver (and in the future, svFSI) and another that mimics parameter estimation/UQ by changing parameters, running simulations, parsing results, making another parameter update, etc. 

I also updated the documentation to highlight new features.

Issue #30

### CODE REVIEW

**Review by richterjakob — CHANGES_REQUESTED** [review]
Thanks a lot for adding this 🙏

I just have one question: Would't it make more sense to also use cmake for the tests, so we don't have two different build systems in one repository?

**Comment by menon-karthik** [comment]
> Thanks a lot for adding this 🙏
> 
> I just have one question: Would't it make more sense to also use cmake for the tests, so we don't have two different build systems in one repository?

Oh you mean including the test directories in the main CMakeLists? If yes, that's a good idea and I didn't think of it! I can do that.

**Comment by richterjakob** [comment]
> > Thanks a lot for adding this 🙏
> > I just have one question: Would't it make more sense to also use cmake for the tests, so we don't have two different build systems in one repository?
> 
> Oh you mean including the test directories in the main CMakeLists? If yes, that's a good idea and I didn't think of it! I can do that.

I wouldn't include it in the top level `CMakeLists.txt` but maybe add an independent `CMakeLists.txt` to `tests/test_interface` That can be used to build the tests.

**Review by richterjakob — APPROVED** [review]
Thanks for making the changes. Everything looks good to me!

**Pull request merged**
