### PR TITLE
Add installer

### LINKED ISSUE #50: Add CMake commands for building installer
There are currently no CMake commands to build an installer for the `svzerodsolver` and `svzerodcalibrator` executables. 

I will add CMake CPack commands to build the installers.

### PR DESCRIPTION
**Pull request by mrp089**
Eventually closes #50. Work in progress to check GitHub Actions.

### CODE REVIEW

**Comment by mrp089** [comment]
Addresses #35.

**Comment by mrp089** [comment]
I added the interface library to `./lib`. @ktbolt, do you know how to remove the `./include` and `./shared` folders?

**Comment by mrp089** [comment]
I tried a couple of things:
```
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN NO)
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED NO)
set(CPACK_ARCHIVE_COMPONENT_INSTALL NO)
set(CPACK_IGNORE_FILES "shared/*" "include/*")
set(CPACK_COMPONENTS_IGNORE_GROUPS "shared;include")
set(CPACK_SOURCE_IGNORE_FILES "*/_deps/*")
```
I still get the `include` and `shared` folders.

I'd be fine to live with that since we get what we need (`bin/svzerodcalibrator`, `bin/svzerodsolver`, `lib/libsvzero_interface.dylib`), and the installer is still only `2.2M` big.

**Comment by ktbolt** [comment]
@mrp089 Let me have a look. 

I think `interface` needs to have an include file added to the installer too.

**Comment by mrp089** [comment]
I think the source of these includes might be in the main `CMakeLists.txt`, not in the distribution one.

**Comment by ktbolt** [comment]
I modified `svZeroDPlus/distribution/CMakeLists.txt` with
```
  # create the installer for both solver and calibrator
  install(TARGETS svzerodsolver svzerodcalibrator
          RUNTIME DESTINATION bin
          COMPONENT applications)

  # add the interface header
  install(FILES ${CMAKE_CURRENT_SOURCE_DIR}/../src/interface/interface.h DESTINATION include COMPONENT headers)

  # add interface library
  if(APPLE)
    install(FILES ${CMAKE_BINARY_DIR}/src/interface/libsvzero_interface.dylib DESTINATION lib COMPONENT libraries)
  elseif(LINUX)
    install(FILES ${CMAKE_BINARY_DIR}/src/interface/libsvzero_interface.so DESTINATION lib COMPONENT libraries)
  endif(APPLE)

  set(CPACK_COMPONENTS_ALL applications libraries headers)
```

The installer now creates just the needed directories 
```
$ ls /usr/local/sv/svZeroDPlus/2023-10-13
bin/		include/	lib/

/usr/local/sv/svZeroDPlus/2023-10-13/bin:
svzerodcalibrator*	svzerodsolver*

/usr/local/sv/svZeroDPlus/2023-10-13/include:
interface.h

/usr/local/sv/svZeroDPlus/2023-10-13/lib:
libsvzero_interface.dylib
```

**Comment by mrp089** [comment]
@ktbolt, I made those changes (as a maintainer, you can also directly commit/push on my feature branch, which will appear in this pull request). I get:
```
/usr/local/sv/svZeroDPlus/2023-10-16/bin:
svzerodcalibrator	svzerodsolver

/usr/local/sv/svZeroDPlus/2023-10-16/include:
interface.h

/usr/local/sv/svZeroDPlus/2023-10-16/lib:
libsvzero_interface.dylib
```

Ready to merge from my side!

**Comment by mrp089** [comment]
I've never used `cmake` or built installers for Windows.

All I can tell you is that `pip install ...` worked fine with `svZeroDSolver` under Ubuntu, Mac OS, and Windows. We still have the option to do that here.

**Comment by ktbolt** [comment]
I will later add support for Windows.

**Review by ktbolt — APPROVED** [review]
Even though there is no Windows support let's merge it so I can add this later.

**Pull request merged**
